# Generated by Django 5.2.4 on 2026-04-06 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'categorias_gasto',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pagado', max_length=10)),
                ('fecha', models.DateField()),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='finanzas.categoriagasto')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gastos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('monto_apertura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notas_apertura', models.TextField(blank=True)),
                ('notas_cierre', models.TextField(blank=True)),
                ('hora_apertura', models.DateTimeField(auto_now_add=True)),
                ('hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'caja_diaria',
                'ordering': ['-fecha'],
                'unique_together': {('cajero', 'fecha')},
            },
        ),
    ]
