"""
Django settings for gestech project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2xn!z0rur!*wk(@8)7pog9^sp&e7jr1y*zddgsyau+@ueth+#1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #Frameworks
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',


    #Carpetas creadas
    'usuarios',
    'catalogo',
    'inventario',
    'compras',
    'ventas',
    'reparaciones',
    'finanzas',
    'pagos'
]

MIDDLEWARE = [
    #1 es el cambio
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    

]

ROOT_URLCONF = 'gestech.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestech.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gestech_db',   
        'USER': 'root',          
        'PASSWORD': '1234',          
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Le dice a Django que use nuestro modelo de usuario personalizado
AUTH_USER_MODEL = 'usuarios.Usuario'

# Configuración de la API
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Los endpoints usan tokens JWT para autenticar
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Permite que React (en otro puerto) se comunique con Django
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',  # puerto por defecto de Vite/React
    'http://localhost:3000',  # puerto alternativo de React
]

MERCADOPAGO_ACCESS_TOKEN  = 'APP_USR-8987935352958958-040603-942cc075266f88016a9a91eaf0a1f00d-3302873853'
MERCADOPAGO_WEBHOOK_SECRET = '68496e8569780d949d40b96bee1337fba4cf0521fdbbfe587c8d26daf8a29976'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


