# Generated by Django 6.0.3 on 2026-03-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
