# Generated by Django 5.2.4 on 2026-04-06 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_alter_categoriaproducto_id_alter_producto_id_and_more'),
        ('ventas', '0003_venta_mp_payment_id_venta_mp_preference_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenReparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_or', models.CharField(max_length=20, unique=True)),
                ('tipo_equipo', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('descripcion_falla', models.TextField()),
                ('accesorios', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('trabajo_realizado', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('diagnostico', 'En diagnóstico'), ('en_proceso', 'En proceso'), ('esperando', 'Esperando pieza'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('sin_reparar', 'Sin reparar')], default='recibido', max_length=20)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('express', 'Express')], default='normal', max_length=10)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_piezas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_prometida', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones', to='ventas.cliente')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordenes_reparacion',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='PiezaUsada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='reparaciones.ordenreparacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
            ],
            options={
                'db_table': 'piezas_usadas',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteReparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('boleta', 'Boleta'), ('factura', 'Factura'), ('ticket', 'Ticket')], default='ticket', max_length=10)),
                ('serie', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('emitido', 'Emitido'), ('anulado', 'Anulado')], default='emitido', max_length=10)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante', to='reparaciones.ordenreparacion')),
            ],
            options={
                'db_table': 'comprobantes_reparacion',
                'unique_together': {('tipo_comprobante', 'serie', 'numero')},
            },
        ),
    ]
